cd build
make install
cd -

cd build_i86
make install
cd -
# MESA_VK_DEVICE_SELECT=10005:0!
# ENABLE_ETC2=1 BCN_TRANSCODE_TO_ETC2=1 BCN_COMPUTE_IMAGE_VIEW=0 BCN_LAYER_LOG_LEVEL=info,error ENABLE_BCN_COMPUTE=1
ENABLE_ETC2=1 BCN_TRANSCODE_TO_ASTC=1 ENABLE_BCN_COMPUTE=1 VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation ~/Documents/Godot/etc-2-demo/etc2demo.x86_64
