#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer InputBuffer {
    uint input_pixels[];
};
layout(std430, set = 0, binding = 1) writeonly buffer OutputBuffer {
    uint output_pixels[];
};

layout(push_constant) uniform PushConstants {
    uint width;
    uint height;
    uint id;
} constants;

const uint FONT_COLUMNS[50] = uint[](
    0x3E, 0x41, 0x41, 0x41, 0x3E, // 0
    0x00, 0x42, 0x7F, 0x40, 0x00, // 1
    0x42, 0x61, 0x51, 0x49, 0x46, // 2
    0x22, 0x41, 0x49, 0x49, 0x36, // 3
    0x18, 0x14, 0x12, 0x7F, 0x10, // 4
    0x27, 0x45, 0x45, 0x45, 0x39, // 5
    0x3E, 0x49, 0x49, 0x49, 0x30, // 6
    0x01, 0x01, 0x79, 0x05, 0x03, // 7
    0x36, 0x49, 0x49, 0x49, 0x36, // 8
    0x06, 0x49, 0x49, 0x49, 0x3E  // 9
);

int get_font_pixel(uint digit, ivec2 font_coord) {
    if (digit > 9U || font_coord.x < 0 || font_coord.x >= 5 || font_coord.y < 0 || font_coord.y >= 7) {
        return 0;
    }
    uint column = FONT_COLUMNS[digit * 5 + font_coord.x];
    return int((column >> (6 - font_coord.y)) & 1U);
}

void main() {
    ivec2 pixel_coord = ivec2(gl_GlobalInvocationID.xy);
    if (pixel_coord.x >= int(constants.width) || pixel_coord.y >= int(constants.height)) {
        return;
    }

    uint linear_index = uint(pixel_coord.y * int(constants.width) + pixel_coord.x);
    uint raw_input_color = input_pixels[linear_index];
    vec4 final_color = unpackUnorm4x8(raw_input_color);

    int glyph_spacing = 6;
    int watermark_width = 4 * glyph_spacing;
    int tile_width = watermark_width + 4 * glyph_spacing * 2;
    int tile_height = 56;

    int tile_x = pixel_coord.x / tile_width;
    int tile_y = pixel_coord.y / tile_height;
    int local_x = pixel_coord.x % tile_width;
    int local_y = pixel_coord.y % tile_height;

    bool should_draw = false;
    if (local_y < 7) {
        should_draw = true;
    }
    if (should_draw && local_x < watermark_width) {
        int slot = local_x / glyph_spacing;
        ivec2 font_coord = ivec2(local_x % glyph_spacing, 7 - local_y % 7);

        uint value = constants.id % 10000U;
        uint digit = 0U;
        if (slot == 0) digit = (value / 1000U) % 10U;
        if (slot == 1) digit = (value / 100U) % 10U;
        if (slot == 2) digit = (value / 10U) % 10U;
        if (slot == 3) digit = value % 10U;
        if (get_font_pixel(digit, font_coord) == 1) {
            final_color = vec4(1.0, 1.0, 1.0, 1.0);
        } else {
            final_color = vec4(0.0, 0.0, 0.0, 1.0);
        }
    }

    // Border with a corner on the bottom right for orientation (in case the texture is flipped)
    if (local_y == 7 && local_x < watermark_width) {
        final_color = vec4(1, 1, 1, 1.0);
    }
    if (local_x == watermark_width + 1 && local_y < 8) {
        final_color = vec4(1, 1, 1, 1.0);
    }

    output_pixels[linear_index] = packUnorm4x8(final_color);
}
